### ISSUE TITLE
spoof list returns nothing in ubuntu 18.04

### ISSUE THREAD

**Issue by x1alien** [feross/spoof#34]
And executing with sudo privileges returned:  

> ~$ sudo spoof list
sudo: spoof: command not found

I also have ifconfig installed.

**Comment by j0ma** [comment]
Same for Manjaro Linux! Installed via `npm`.

```
% sudo spoof list                                           

```

same goes for running it without `sudo`:

```
% spoof list                                   

```

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
